dist: bionic

language: node_js
node_js:
  - 16

sudo: false

addons:
  chrome: stable
  # https://github.com/Automattic/node-canvas
  # canvas is indirectly required by protractor-image-comparison
  apt:
    packages:
      - libpango1.0-dev
      - libjpeg-dev
      - build-essential
      - libcairo2-dev
      - libpango1.0-dev
      - libjpeg-dev
      - libgif-dev
      - librsvg2-dev

install:
  - npm install
  - node ./node_modules/.bin/webdriver-manager update --versions.chrome=$(google-chrome --version | sed 's/Google Chrome //')

script:
  - xvfb-run npm run ng e2e -- --webdriver-update=false
