language: node_js
node_js:
  - 12

dist: trusty
sudo: false

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
    - node_modules

install:
  - npm ci
script:
  - xvfb-run npm run e2e
