dist: bionic

language: node_js
node_js:
  - 14

sudo: false

addons:
  chrome: stable


install:
  - npm install

before_script:
  - webdriver-manager update 
  #--versions.chrome=84.0.4147.30

script:
  - xvfb-run npm run e2e
