dist: bionic

language: node_js
node_js:
  - 16

sudo: false

addons:
  chrome: stable
  apt:
    packages:
      - libpango1.0-dev
      - libjpeg-dev

install:
  - npm install
  - node ./node_modules/.bin/webdriver-manager update --versions.chrome=$(google-chrome --version | sed 's/Google Chrome //')

script:
  - xvfb-run npm run ng e2e -- --webdriver-update=false
