language: node_js
node_js:
  - lts/*

dist: xenial
sudo: false

addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - webdriver-manager update 
  #--versions.chrome=84.0.4147.30

script:
  - xvfb-run npm run e2e
