dist: bionic

language: node_js
node_js:
  - 14

sudo: false

addons:
  chrome: stable

install:
  - npm install
  - node ./node_modules/.bin/webdriver-manager update --versions.chrome=90.0.4430.24

script:
  - xvfb-run npm run ng e2e -- --webdriver-update=false
